# 127.0.0.1 redirected to posts.com in etc/hosts file
@url = http://posts.com 



# POSTS

GET {{url}}/posts
Content-Type: application/json
###

POST {{url}}/posts
Content-Type: application/json

{
  "title": "new post"
}
###


# COMMENTS

GET {{url}}/posts/123/comments
Content-Type: application/json
###

POST {{url}}/posts/123/comments
Content-Type: application/json

{
  "content": "comment 2"
}
###