@postsBaseUrl = http://localhost:4000
@commentsBaseUrl = http://localhost:4001


# POSTS

GET {{postsBaseUrl}}/posts
Content-Type: application/json
###

POST {{postsBaseUrl}}/posts
Content-Type: application/json

{
  "title": "new post"
}
###


# COMMENTS

GET {{commentsBaseUrl}}/posts/123/comments
Content-Type: application/json
###

POST {{commentsBaseUrl}}/posts/123/comments
Content-Type: application/json

{
  "content": "comment 2"
}
###